-- Generated by Oracle SQL Developer Data Modeler 22.2.0.165.1149
--   at:        2023-05-02 16:46:55 AEST
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c
--   created by:
--              Krishna Manogaran 31500153 kman0030
--              David Newbound 33120544 dnew0011
--              Peter Roberts 31490514 prob0006
-- Capture run of script in file called cui_schema_output.txt

set echo on
SPOOL cui_schema_output.txt

DROP TABLE bin CASCADE CONSTRAINTS;

DROP TABLE bin_collection CASCADE CONSTRAINTS;

DROP TABLE bin_supply CASCADE CONSTRAINTS;

DROP TABLE contract CASCADE CONSTRAINTS;

DROP TABLE day_report CASCADE CONSTRAINTS;

DROP TABLE driver CASCADE CONSTRAINTS;

DROP TABLE local_authority CASCADE CONSTRAINTS;

DROP TABLE owner CASCADE CONSTRAINTS;

DROP TABLE property CASCADE CONSTRAINTS;

DROP TABLE property_bin CASCADE CONSTRAINTS;

DROP TABLE street CASCADE CONSTRAINTS;

DROP TABLE title_deed CASCADE CONSTRAINTS;

DROP TABLE truck CASCADE CONSTRAINTS;

DROP TABLE truck_auth CASCADE CONSTRAINTS;

DROP TABLE waste CASCADE CONSTRAINTS;

DROP TABLE waste_collection CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE bin (
    bin_size          NUMBER(3) NOT NULL,
    waste_type_id     VARCHAR2(2) NOT NULL,
    bin_standard_cost NUMBER(3) NOT NULL
);

COMMENT ON COLUMN bin.bin_size IS
    'Size of the bin in litres';

COMMENT ON COLUMN bin.waste_type_id IS
    'Waste types'' id';

COMMENT ON COLUMN bin.bin_standard_cost IS
    'Standard cost of a bin';

ALTER TABLE bin ADD CONSTRAINT bin_pk PRIMARY KEY ( bin_size,
                                                    waste_type_id );

CREATE TABLE bin_collection (
    prop_bin_rfid_tag CHAR(16) NOT NULL,
    coll_weight       NUMBER(4),
    overweight        CHAR(1 CHAR),
    day_report_no     NUMBER(7) NOT NULL
);

ALTER TABLE bin_collection
    ADD CONSTRAINT chk_overweight CHECK ( overweight IN ( 'N', 'Y' ) );

COMMENT ON COLUMN bin_collection.prop_bin_rfid_tag IS
    'RFID tag of the property bin';

COMMENT ON COLUMN bin_collection.coll_weight IS
    'Weight of this garbage collection in kilograms';

COMMENT ON COLUMN bin_collection.overweight IS
    'Indication if the bin collections is flagged as overweight (Y) or not (N)';

COMMENT ON COLUMN bin_collection.day_report_no IS
    'Surrogate key for the day_report';

ALTER TABLE bin_collection ADD CONSTRAINT bin_collection_pk PRIMARY KEY ( prop_bin_rfid_tag,
                                                                          day_report_no );

CREATE TABLE bin_supply (
    bin_supply_no   NUMBER(7) NOT NULL,
    bin_supply_cost NUMBER(3) NOT NULL,
    contract_id     VARCHAR2(6) NOT NULL,
    bin_size        NUMBER(3) NOT NULL,
    waste_type_id   VARCHAR2(2) NOT NULL
);

COMMENT ON COLUMN bin_supply.bin_supply_no IS
    'surrogate key for bin supply';

COMMENT ON COLUMN bin_supply.bin_supply_cost IS
    'Supply cost of a bin';

COMMENT ON COLUMN bin_supply.contract_id IS
    'Contract ID

potential for 999,999 contracts';

COMMENT ON COLUMN bin_supply.bin_size IS
    'Size of the bin in litres';

COMMENT ON COLUMN bin_supply.waste_type_id IS
    'Waste types'' id';

ALTER TABLE bin_supply ADD CONSTRAINT bin_supply_pk PRIMARY KEY ( bin_supply_no );

ALTER TABLE bin_supply
    ADD CONSTRAINT bin_supply_nk UNIQUE ( contract_id,
                                          bin_size,
                                          waste_type_id );

CREATE TABLE contract (
    contract_id         VARCHAR2(6) NOT NULL,
    contract_start_date DATE NOT NULL,
    contract_end_date   DATE NOT NULL,
    auth_name           VARCHAR2(32) NOT NULL
);

COMMENT ON COLUMN contract.contract_id IS
    'Contract ID

potential for 999,999 contracts';

COMMENT ON COLUMN contract.contract_start_date IS
    'Contract start date';

COMMENT ON COLUMN contract.contract_end_date IS
    'Contract end date';

COMMENT ON COLUMN contract.auth_name IS
    'Local Authority''s name';

ALTER TABLE contract ADD CONSTRAINT contract_pk PRIMARY KEY ( contract_id );

CREATE TABLE day_report (
    day_report_no NUMBER(7) NOT NULL,
    coll_date     DATE NOT NULL,
    contract_id   VARCHAR2(6) NOT NULL,
    waste_type_id VARCHAR2(2) NOT NULL,
    truck_vin     CHAR(17) NOT NULL,
    driver_no     NUMBER(5) NOT NULL
);

COMMENT ON COLUMN day_report.day_report_no IS
    'Surrogate key for the day_report';

COMMENT ON COLUMN day_report.coll_date IS
    'attribute for the collection date';

COMMENT ON COLUMN day_report.contract_id IS
    'Contract ID

potential for 999,999 contracts';

COMMENT ON COLUMN day_report.waste_type_id IS
    'Waste types'' id';

COMMENT ON COLUMN day_report.truck_vin IS
    'Represents the Truck Vehicle Idendification Number

VINs are17 characters long';

COMMENT ON COLUMN day_report.driver_no IS
    'attribute for driver number

potential for 99,999  drivers in CUI';

ALTER TABLE day_report ADD CONSTRAINT day_report_pk PRIMARY KEY ( day_report_no );

ALTER TABLE day_report
    ADD CONSTRAINT day_report_nk UNIQUE ( coll_date,
                                          contract_id,
                                          waste_type_id );

CREATE TABLE driver (
    driver_no         NUMBER(5) NOT NULL,
    driver_licence_no CHAR(10) NOT NULL,
    driver_name       VARCHAR2(32) NOT NULL,
    driver_dob        DATE NOT NULL,
    driver_tfn        CHAR(10) NOT NULL,
    driver_phone      CHAR 
--  WARNING: CHAR size not specified 
     NOT NULL
);

COMMENT ON COLUMN driver.driver_no IS
    'attribute for driver number

potential for 99,999  drivers in CUI';

COMMENT ON COLUMN driver.driver_licence_no IS
    'attribute for driver licence number';

COMMENT ON COLUMN driver.driver_name IS
    'attribute for the driver''s name';

COMMENT ON COLUMN driver.driver_dob IS
    'attribute for the driver''s date of birth';

COMMENT ON COLUMN driver.driver_tfn IS
    'attribute for the driver''s tfn';

COMMENT ON COLUMN driver.driver_phone IS
    'attribute for driver phone

as per the example, 10 digits. Mobile number.';

ALTER TABLE driver ADD CONSTRAINT driver_pk PRIMARY KEY ( driver_no );

CREATE TABLE local_authority (
    auth_name            VARCHAR2(32) NOT NULL,
    auth_type            CHAR(1) NOT NULL,
    auth_phone_num       VARCHAR2(10) NOT NULL,
    auth_area            NUMBER(4) NOT NULL,
    auth_ceo_given_name  VARCHAR2(32) NOT NULL,
    auth_ceo_family_name VARCHAR2(32) NOT NULL
);

ALTER TABLE local_authority
    ADD CONSTRAINT chk_auth_type CHECK ( auth_type IN ( 'B', 'C', 'D', 'S', 'T' ) );

COMMENT ON COLUMN local_authority.auth_name IS
    'Local Authority''s name';

COMMENT ON COLUMN local_authority.auth_type IS
    'Local Authority type';

COMMENT ON COLUMN local_authority.auth_phone_num IS
    'Local Authority phone number

could be a landline, so varchar is needed';

COMMENT ON COLUMN local_authority.auth_area IS
    'Local Authority area in square kilometres';

COMMENT ON COLUMN local_authority.auth_ceo_given_name IS
    'Local Authority CEO''s given name';

COMMENT ON COLUMN local_authority.auth_ceo_family_name IS
    'Local Authority CEO''s family name';

ALTER TABLE local_authority ADD CONSTRAINT local_authority_pk PRIMARY KEY ( auth_name );

CREATE TABLE owner (
    owner_id         VARCHAR2(32) NOT NULL,
    owner_first_name VARCHAR2(32) NOT NULL,
    owner_last_name  VARCHAR2(32) NOT NULL,
    owner_email      VARCHAR2(64) NOT NULL,
    owner_phone_num  VARCHAR2(10) NOT NULL
);

COMMENT ON COLUMN owner.owner_id IS
    'Owner''s ID';

COMMENT ON COLUMN owner.owner_first_name IS
    'Owner''s first name';

COMMENT ON COLUMN owner.owner_last_name IS
    'Owner''s last name';

COMMENT ON COLUMN owner.owner_email IS
    'Owner''s email';

COMMENT ON COLUMN owner.owner_phone_num IS
    'Owner''s phone number';

ALTER TABLE owner ADD CONSTRAINT owner_pk PRIMARY KEY ( owner_id );

CREATE TABLE property (
    property_no        NUMBER(7) NOT NULL,
    prop_street_number VARCHAR2(10) NOT NULL,
    street_id          VARCHAR2(4) NOT NULL,
    auth_name          VARCHAR2(32) NOT NULL
);

COMMENT ON COLUMN property.property_no IS
    'Surrogate key for property number';

COMMENT ON COLUMN property.prop_street_number IS
    'Street number for the property

10 characters of space given the nature of some street numbers';

COMMENT ON COLUMN property.street_id IS
    'Street ID';

COMMENT ON COLUMN property.auth_name IS
    'Local Authority''s name';

ALTER TABLE property ADD CONSTRAINT property_pk PRIMARY KEY ( property_no );

ALTER TABLE property
    ADD CONSTRAINT property_nk UNIQUE ( street_id,
                                        auth_name,
                                        prop_street_number );

CREATE TABLE property_bin (
    prop_bin_rfid_tag       CHAR(16) NOT NULL,
    prop_bin_supply_date    DATE NOT NULL,
    prop_bin_replace_reason CHAR(2) NOT NULL,
    bin_size                NUMBER(3) NOT NULL,
    waste_type_id           VARCHAR2(2) NOT NULL,
    property_no             NUMBER(7) NOT NULL
);

ALTER TABLE property_bin
    ADD CONSTRAINT chk_prob_bin_replace_reason CHECK ( prop_bin_replace_reason IN ( 'BF', 'DO', 'DW', 'ST' ) );

COMMENT ON COLUMN property_bin.prop_bin_rfid_tag IS
    'RFID tag of the property bin';

COMMENT ON COLUMN property_bin.prop_bin_supply_date IS
    'Date the property bin was supplied';

COMMENT ON COLUMN property_bin.prop_bin_replace_reason IS
    'Reason this property bin was replaced, if any';

COMMENT ON COLUMN property_bin.bin_size IS
    'Size of the bin in litres';

COMMENT ON COLUMN property_bin.waste_type_id IS
    'Waste types'' id';

COMMENT ON COLUMN property_bin.property_no IS
    'Surrogate key for property number';

ALTER TABLE property_bin ADD CONSTRAINT property_bin_pk PRIMARY KEY ( prop_bin_rfid_tag );

CREATE TABLE street (
    street_id        VARCHAR2(4) NOT NULL,
    auth_name        VARCHAR2(32) NOT NULL,
    street_name      VARCHAR2(32) NOT NULL,
    street_length    NUMBER(4) NOT NULL,
    street_surface   CHAR(1) NOT NULL,
    street_num_lanes NUMBER(3) NOT NULL
);

ALTER TABLE street
    ADD CONSTRAINT chk_street_surface CHECK ( street_surface IN ( 'A', 'C', 'U' ) );

COMMENT ON COLUMN street.street_id IS
    'Street ID';

COMMENT ON COLUMN street.auth_name IS
    'Local Authority''s name';

COMMENT ON COLUMN street.street_name IS
    'Street name';

COMMENT ON COLUMN street.street_length IS
    'Street length in metres';

COMMENT ON COLUMN street.street_surface IS
    'Street surface type';

COMMENT ON COLUMN street.street_num_lanes IS
    'Street number of lanes';

ALTER TABLE street ADD CONSTRAINT street_pk PRIMARY KEY ( street_id,
                                                          auth_name );

CREATE TABLE title_deed (
    owner_id    VARCHAR2(32) NOT NULL,
    property_no NUMBER(7) NOT NULL
);

COMMENT ON TABLE title_deed IS
    'This was done to avoid the many to many between property and owner';

COMMENT ON COLUMN title_deed.owner_id IS
    'Owner''s ID';

COMMENT ON COLUMN title_deed.property_no IS
    'Surrogate key for property number';

ALTER TABLE title_deed ADD CONSTRAINT title_deed_pk PRIMARY KEY ( owner_id,
                                                                  property_no );

CREATE TABLE truck (
    truck_vin   CHAR(17) NOT NULL,
    truck_rego  CHAR(10) NOT NULL,
    truck_make  VARCHAR2(32) NOT NULL,
    truck_model VARCHAR2(64) NOT NULL,
    truck_year  DATE NOT NULL
);

COMMENT ON COLUMN truck.truck_vin IS
    'Represents the Truck Vehicle Idendification Number

VINs are17 characters long';

COMMENT ON COLUMN truck.truck_rego IS
    'Attribute to represent the registration number of a truck

Chose Char(10) as registration numbers are about 9 long in the form, but I wanted some buffer.';

COMMENT ON COLUMN truck.truck_make IS
    'Attribute to represent truck make';

COMMENT ON COLUMN truck.truck_model IS
    'attribute to represent truck_model';

COMMENT ON COLUMN truck.truck_year IS
    'Attribute to represent the truck year

Date or char(4), I can''t remember, probably date';

ALTER TABLE truck ADD CONSTRAINT truck_pk PRIMARY KEY ( truck_vin );

CREATE TABLE truck_auth (
    truck_vin CHAR(17) NOT NULL,
    driver_no NUMBER(5) NOT NULL
);

COMMENT ON COLUMN truck_auth.truck_vin IS
    'Represents the Truck Vehicle Idendification Number

VINs are17 characters long';

COMMENT ON COLUMN truck_auth.driver_no IS
    'attribute for driver number

potential for 99,999  drivers in CUI';

ALTER TABLE truck_auth ADD CONSTRAINT truck_auth_pk PRIMARY KEY ( truck_vin,
                                                                  driver_no );

CREATE TABLE waste (
    waste_type_id          VARCHAR2(2) NOT NULL,
    waste_type_description VARCHAR2(32) NOT NULL
);

COMMENT ON COLUMN waste.waste_type_id IS
    'Waste types'' id';

COMMENT ON COLUMN waste.waste_type_description IS
    'Waste types'' description';

ALTER TABLE waste ADD CONSTRAINT waste_pk PRIMARY KEY ( waste_type_id );

CREATE TABLE waste_collection (
    contract_id                  VARCHAR2(6) NOT NULL,
    waste_type_id                VARCHAR2(2) NOT NULL,
    waste_collection_cost_per_kg NUMBER(3, 2) NOT NULL,
    coll_freq                    CHAR 
--  WARNING: CHAR size not specified 
     NOT NULL
);

ALTER TABLE waste_collection
    ADD CONSTRAINT chk_coll_freq CHECK ( coll_freq IN ( 'F', 'M', 'W' ) );

COMMENT ON COLUMN waste_collection.contract_id IS
    'Contract ID

potential for 999,999 contracts';

COMMENT ON COLUMN waste_collection.waste_type_id IS
    'Waste types'' id';

COMMENT ON COLUMN waste_collection.waste_collection_cost_per_kg IS
    'Collection cost per kg for waste types';

COMMENT ON COLUMN waste_collection.coll_freq IS
    'Collection frequency';

ALTER TABLE waste_collection ADD CONSTRAINT waste_collection_pk PRIMARY KEY ( contract_id,
                                                                              waste_type_id );

ALTER TABLE bin_supply
    ADD CONSTRAINT bin_bin_supply FOREIGN KEY ( bin_size,
                                                waste_type_id )
        REFERENCES bin ( bin_size,
                         waste_type_id );

ALTER TABLE property_bin
    ADD CONSTRAINT bin_property_bin FOREIGN KEY ( bin_size,
                                                  waste_type_id )
        REFERENCES bin ( bin_size,
                         waste_type_id );

ALTER TABLE bin_supply
    ADD CONSTRAINT contract_bin_supply FOREIGN KEY ( contract_id )
        REFERENCES contract ( contract_id );

ALTER TABLE waste_collection
    ADD CONSTRAINT contract_waste_collection FOREIGN KEY ( contract_id )
        REFERENCES contract ( contract_id );

ALTER TABLE bin_collection
    ADD CONSTRAINT day_report_bin_collection FOREIGN KEY ( day_report_no )
        REFERENCES day_report ( day_report_no );

ALTER TABLE day_report
    ADD CONSTRAINT driver_day_report FOREIGN KEY ( driver_no )
        REFERENCES driver ( driver_no );

ALTER TABLE truck_auth
    ADD CONSTRAINT driver_truck_auth FOREIGN KEY ( driver_no )
        REFERENCES driver ( driver_no );

ALTER TABLE contract
    ADD CONSTRAINT local_authority_contract FOREIGN KEY ( auth_name )
        REFERENCES local_authority ( auth_name );

ALTER TABLE street
    ADD CONSTRAINT local_authority_streets FOREIGN KEY ( auth_name )
        REFERENCES local_authority ( auth_name );

ALTER TABLE title_deed
    ADD CONSTRAINT owner_title_deed FOREIGN KEY ( owner_id )
        REFERENCES owner ( owner_id );

ALTER TABLE bin_collection
    ADD CONSTRAINT property_bin_bin_collection FOREIGN KEY ( prop_bin_rfid_tag )
        REFERENCES property_bin ( prop_bin_rfid_tag );

ALTER TABLE property_bin
    ADD CONSTRAINT property_property_bin FOREIGN KEY ( property_no )
        REFERENCES property ( property_no );

ALTER TABLE title_deed
    ADD CONSTRAINT property_title_deed FOREIGN KEY ( property_no )
        REFERENCES property ( property_no );

ALTER TABLE property
    ADD CONSTRAINT street_property FOREIGN KEY ( street_id,
                                                 auth_name )
        REFERENCES street ( street_id,
                            auth_name );

ALTER TABLE day_report
    ADD CONSTRAINT truck_day_report FOREIGN KEY ( truck_vin )
        REFERENCES truck ( truck_vin );

ALTER TABLE truck_auth
    ADD CONSTRAINT truck_truck_auth FOREIGN KEY ( truck_vin )
        REFERENCES truck ( truck_vin );

ALTER TABLE bin
    ADD CONSTRAINT waste_bin FOREIGN KEY ( waste_type_id )
        REFERENCES waste ( waste_type_id );

ALTER TABLE day_report
    ADD CONSTRAINT waste_coll_day_rep FOREIGN KEY ( contract_id,
                                                    waste_type_id )
        REFERENCES waste_collection ( contract_id,
                                      waste_type_id );

ALTER TABLE waste_collection
    ADD CONSTRAINT waste_waste_collection FOREIGN KEY ( waste_type_id )
        REFERENCES waste ( waste_type_id );

SPOOL off
set echo off

-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            16
-- CREATE INDEX                             0
-- ALTER TABLE                             43
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 2
